/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppAboutRouteImport } from './routes/_app/about'
import { Route as AppAccountRouteImport } from './routes/_app/account'
import { Route as AppBrandsRouteImport } from './routes/_app/brands'
import { Route as AppCareersRouteImport } from './routes/_app/careers'
import { Route as AppCartRouteImport } from './routes/_app/cart'
import { Route as AppContactRouteImport } from './routes/_app/contact'
import { Route as AppCorporateRouteImport } from './routes/_app/corporate'
import { Route as AppForgotPasswordRouteImport } from './routes/_app/forgot-password'
import { Route as AppHelpRouteImport } from './routes/_app/help'
import { Route as AppLoginRouteImport } from './routes/_app/login'
import { Route as AppPrivacyRouteImport } from './routes/_app/privacy'
import { Route as AppRegisterRouteImport } from './routes/_app/register'
import { Route as AppReturnPolicyRouteImport } from './routes/_app/return-policy'
import { Route as AppReturnsRouteImport } from './routes/_app/returns'
import { Route as AppSearchRouteImport } from './routes/_app/search'
import { Route as AppShippingRouteImport } from './routes/_app/shipping'
import { Route as AppStoresRouteImport } from './routes/_app/stores'
import { Route as AppTermsRouteImport } from './routes/_app/terms'
import { Route as AppWishlistRouteImport } from './routes/_app/wishlist'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminBannersRouteImport } from './routes/admin/banners'
import { Route as AdminCategoriesRouteImport } from './routes/admin/categories'
import { Route as AdminCouponsRouteImport } from './routes/admin/coupons'
import { Route as AdminCustomersRouteImport } from './routes/admin/customers'
import { Route as AdminDiscountsRouteImport } from './routes/admin/discounts'
import { Route as AdminInventoryRouteImport } from './routes/admin/inventory'
import { Route as AdminOrdersRouteImport } from './routes/admin/orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin/payments'
import { Route as AdminProductsRouteImport } from './routes/admin/products'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminStoresRouteImport } from './routes/admin/stores'
import { Route as AppAccountIndexRouteImport } from './routes/_app/account/index'
import { Route as AppAccountAddressesRouteImport } from './routes/_app/account/addresses'
import { Route as AppAccountNotificationsRouteImport } from './routes/_app/account/notifications'
import { Route as AppAccountPaymentMethodsRouteImport } from './routes/_app/account/payment-methods'
import { Route as AppAccountProfileRouteImport } from './routes/_app/account/profile'
import { Route as AppCategorySlugRouteImport } from './routes/_app/category/$slug'
import { Route as AppCheckoutIndexRouteImport } from './routes/_app/checkout/index'
import { Route as AppCheckoutSuccessRouteImport } from './routes/_app/checkout/success'
import { Route as AppOrdersIndexRouteImport } from './routes/_app/orders/index'
import { Route as AppOrdersIdRouteImport } from './routes/_app/orders/$id'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppProductsIdRouteImport } from './routes/_app/products/$id'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppAboutRoute = AppAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AppRoute,
} as any)
const AppAccountRoute = AppAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AppRoute,
} as any)
const AppBrandsRoute = AppBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => AppRoute,
} as any)
const AppCareersRoute = AppCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AppRoute,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => AppRoute,
} as any)
const AppContactRoute = AppContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => AppRoute,
} as any)
const AppCorporateRoute = AppCorporateRouteImport.update({
  id: '/corporate',
  path: '/corporate',
  getParentRoute: () => AppRoute,
} as any)
const AppForgotPasswordRoute = AppForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppLoginRoute = AppLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AppRoute,
} as any)
const AppPrivacyRoute = AppPrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => AppRoute,
} as any)
const AppRegisterRoute = AppRegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnPolicyRoute = AppReturnPolicyRouteImport.update({
  id: '/return-policy',
  path: '/return-policy',
  getParentRoute: () => AppRoute,
} as any)
const AppReturnsRoute = AppReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => AppRoute,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppShippingRoute = AppShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => AppRoute,
} as any)
const AppStoresRoute = AppStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AppRoute,
} as any)
const AppTermsRoute = AppTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => AppRoute,
} as any)
const AppWishlistRoute = AppWishlistRouteImport.update({
  id: '/wishlist',
  path: '/wishlist',
  getParentRoute: () => AppRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminBannersRoute = AdminBannersRouteImport.update({
  id: '/banners',
  path: '/banners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCouponsRoute = AdminCouponsRouteImport.update({
  id: '/coupons',
  path: '/coupons',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDiscountsRoute = AdminDiscountsRouteImport.update({
  id: '/discounts',
  path: '/discounts',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInventoryRoute = AdminInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStoresRoute = AdminStoresRouteImport.update({
  id: '/stores',
  path: '/stores',
  getParentRoute: () => AdminRoute,
} as any)
const AppAccountIndexRoute = AppAccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountAddressesRoute = AppAccountAddressesRouteImport.update({
  id: '/addresses',
  path: '/addresses',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountNotificationsRoute = AppAccountNotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppAccountPaymentMethodsRoute =
  AppAccountPaymentMethodsRouteImport.update({
    id: '/payment-methods',
    path: '/payment-methods',
    getParentRoute: () => AppAccountRoute,
  } as any)
const AppAccountProfileRoute = AppAccountProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppAccountRoute,
} as any)
const AppCategorySlugRoute = AppCategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutIndexRoute = AppCheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => AppRoute,
} as any)
const AppCheckoutSuccessRoute = AppCheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIndexRoute = AppOrdersIndexRouteImport.update({
  id: '/orders/',
  path: '/orders/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrdersIdRoute = AppOrdersIdRouteImport.update({
  id: '/orders/$id',
  path: '/orders/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/about': typeof AppAboutRoute
  '/account': typeof AppAccountRouteWithChildren
  '/brands': typeof AppBrandsRoute
  '/careers': typeof AppCareersRoute
  '/cart': typeof AppCartRoute
  '/contact': typeof AppContactRoute
  '/corporate': typeof AppCorporateRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/help': typeof AppHelpRoute
  '/login': typeof AppLoginRoute
  '/privacy': typeof AppPrivacyRoute
  '/register': typeof AppRegisterRoute
  '/return-policy': typeof AppReturnPolicyRoute
  '/returns': typeof AppReturnsRoute
  '/search': typeof AppSearchRoute
  '/shipping': typeof AppShippingRoute
  '/stores': typeof AppStoresRoute
  '/terms': typeof AppTermsRoute
  '/wishlist': typeof AppWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/admin/': typeof AdminIndexRoute
  '/account/addresses': typeof AppAccountAddressesRoute
  '/account/notifications': typeof AppAccountNotificationsRoute
  '/account/payment-methods': typeof AppAccountPaymentMethodsRoute
  '/account/profile': typeof AppAccountProfileRoute
  '/category/$slug': typeof AppCategorySlugRoute
  '/checkout/success': typeof AppCheckoutSuccessRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/products/$id': typeof AppProductsIdRoute
  '/account/': typeof AppAccountIndexRoute
  '/checkout/': typeof AppCheckoutIndexRoute
  '/orders/': typeof AppOrdersIndexRoute
  '/products/': typeof AppProductsIndexRoute
}
export interface FileRoutesByTo {
  '/about': typeof AppAboutRoute
  '/brands': typeof AppBrandsRoute
  '/careers': typeof AppCareersRoute
  '/cart': typeof AppCartRoute
  '/contact': typeof AppContactRoute
  '/corporate': typeof AppCorporateRoute
  '/forgot-password': typeof AppForgotPasswordRoute
  '/help': typeof AppHelpRoute
  '/login': typeof AppLoginRoute
  '/privacy': typeof AppPrivacyRoute
  '/register': typeof AppRegisterRoute
  '/return-policy': typeof AppReturnPolicyRoute
  '/returns': typeof AppReturnsRoute
  '/search': typeof AppSearchRoute
  '/shipping': typeof AppShippingRoute
  '/stores': typeof AppStoresRoute
  '/terms': typeof AppTermsRoute
  '/wishlist': typeof AppWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/': typeof AppIndexRoute
  '/admin': typeof AdminIndexRoute
  '/account/addresses': typeof AppAccountAddressesRoute
  '/account/notifications': typeof AppAccountNotificationsRoute
  '/account/payment-methods': typeof AppAccountPaymentMethodsRoute
  '/account/profile': typeof AppAccountProfileRoute
  '/category/$slug': typeof AppCategorySlugRoute
  '/checkout/success': typeof AppCheckoutSuccessRoute
  '/orders/$id': typeof AppOrdersIdRoute
  '/products/$id': typeof AppProductsIdRoute
  '/account': typeof AppAccountIndexRoute
  '/checkout': typeof AppCheckoutIndexRoute
  '/orders': typeof AppOrdersIndexRoute
  '/products': typeof AppProductsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/admin': typeof AdminRouteWithChildren
  '/_app/about': typeof AppAboutRoute
  '/_app/account': typeof AppAccountRouteWithChildren
  '/_app/brands': typeof AppBrandsRoute
  '/_app/careers': typeof AppCareersRoute
  '/_app/cart': typeof AppCartRoute
  '/_app/contact': typeof AppContactRoute
  '/_app/corporate': typeof AppCorporateRoute
  '/_app/forgot-password': typeof AppForgotPasswordRoute
  '/_app/help': typeof AppHelpRoute
  '/_app/login': typeof AppLoginRoute
  '/_app/privacy': typeof AppPrivacyRoute
  '/_app/register': typeof AppRegisterRoute
  '/_app/return-policy': typeof AppReturnPolicyRoute
  '/_app/returns': typeof AppReturnsRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/shipping': typeof AppShippingRoute
  '/_app/stores': typeof AppStoresRoute
  '/_app/terms': typeof AppTermsRoute
  '/_app/wishlist': typeof AppWishlistRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/banners': typeof AdminBannersRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/coupons': typeof AdminCouponsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/discounts': typeof AdminDiscountsRoute
  '/admin/inventory': typeof AdminInventoryRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/stores': typeof AdminStoresRoute
  '/_app/': typeof AppIndexRoute
  '/admin/': typeof AdminIndexRoute
  '/_app/account/addresses': typeof AppAccountAddressesRoute
  '/_app/account/notifications': typeof AppAccountNotificationsRoute
  '/_app/account/payment-methods': typeof AppAccountPaymentMethodsRoute
  '/_app/account/profile': typeof AppAccountProfileRoute
  '/_app/category/$slug': typeof AppCategorySlugRoute
  '/_app/checkout/success': typeof AppCheckoutSuccessRoute
  '/_app/orders/$id': typeof AppOrdersIdRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/account/': typeof AppAccountIndexRoute
  '/_app/checkout/': typeof AppCheckoutIndexRoute
  '/_app/orders/': typeof AppOrdersIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/about'
    | '/account'
    | '/brands'
    | '/careers'
    | '/cart'
    | '/contact'
    | '/corporate'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/privacy'
    | '/register'
    | '/return-policy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/stores'
    | '/terms'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/stores'
    | '/admin/'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/payment-methods'
    | '/account/profile'
    | '/category/$slug'
    | '/checkout/success'
    | '/orders/$id'
    | '/products/$id'
    | '/account/'
    | '/checkout/'
    | '/orders/'
    | '/products/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/about'
    | '/brands'
    | '/careers'
    | '/cart'
    | '/contact'
    | '/corporate'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/privacy'
    | '/register'
    | '/return-policy'
    | '/returns'
    | '/search'
    | '/shipping'
    | '/stores'
    | '/terms'
    | '/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/stores'
    | '/'
    | '/admin'
    | '/account/addresses'
    | '/account/notifications'
    | '/account/payment-methods'
    | '/account/profile'
    | '/category/$slug'
    | '/checkout/success'
    | '/orders/$id'
    | '/products/$id'
    | '/account'
    | '/checkout'
    | '/orders'
    | '/products'
  id:
    | '__root__'
    | '/_app'
    | '/admin'
    | '/_app/about'
    | '/_app/account'
    | '/_app/brands'
    | '/_app/careers'
    | '/_app/cart'
    | '/_app/contact'
    | '/_app/corporate'
    | '/_app/forgot-password'
    | '/_app/help'
    | '/_app/login'
    | '/_app/privacy'
    | '/_app/register'
    | '/_app/return-policy'
    | '/_app/returns'
    | '/_app/search'
    | '/_app/shipping'
    | '/_app/stores'
    | '/_app/terms'
    | '/_app/wishlist'
    | '/admin/analytics'
    | '/admin/banners'
    | '/admin/categories'
    | '/admin/coupons'
    | '/admin/customers'
    | '/admin/discounts'
    | '/admin/inventory'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/products'
    | '/admin/reviews'
    | '/admin/stores'
    | '/_app/'
    | '/admin/'
    | '/_app/account/addresses'
    | '/_app/account/notifications'
    | '/_app/account/payment-methods'
    | '/_app/account/profile'
    | '/_app/category/$slug'
    | '/_app/checkout/success'
    | '/_app/orders/$id'
    | '/_app/products/$id'
    | '/_app/account/'
    | '/_app/checkout/'
    | '/_app/orders/'
    | '/_app/products/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AdminRoute: typeof AdminRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/about': {
      id: '/_app/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AppAboutRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/account': {
      id: '/_app/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AppAccountRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/brands': {
      id: '/_app/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof AppBrandsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/careers': {
      id: '/_app/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof AppCareersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/cart': {
      id: '/_app/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/contact': {
      id: '/_app/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof AppContactRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/corporate': {
      id: '/_app/corporate'
      path: '/corporate'
      fullPath: '/corporate'
      preLoaderRoute: typeof AppCorporateRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/forgot-password': {
      id: '/_app/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof AppForgotPasswordRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/help': {
      id: '/_app/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/login': {
      id: '/_app/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AppLoginRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/privacy': {
      id: '/_app/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof AppPrivacyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/register': {
      id: '/_app/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof AppRegisterRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/return-policy': {
      id: '/_app/return-policy'
      path: '/return-policy'
      fullPath: '/return-policy'
      preLoaderRoute: typeof AppReturnPolicyRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/returns': {
      id: '/_app/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof AppReturnsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/shipping': {
      id: '/_app/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof AppShippingRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/stores': {
      id: '/_app/stores'
      path: '/stores'
      fullPath: '/stores'
      preLoaderRoute: typeof AppStoresRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/terms': {
      id: '/_app/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof AppTermsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/wishlist': {
      id: '/_app/wishlist'
      path: '/wishlist'
      fullPath: '/wishlist'
      preLoaderRoute: typeof AppWishlistRouteImport
      parentRoute: typeof AppRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/banners': {
      id: '/admin/banners'
      path: '/banners'
      fullPath: '/admin/banners'
      preLoaderRoute: typeof AdminBannersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/coupons': {
      id: '/admin/coupons'
      path: '/coupons'
      fullPath: '/admin/coupons'
      preLoaderRoute: typeof AdminCouponsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/discounts': {
      id: '/admin/discounts'
      path: '/discounts'
      fullPath: '/admin/discounts'
      preLoaderRoute: typeof AdminDiscountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inventory': {
      id: '/admin/inventory'
      path: '/inventory'
      fullPath: '/admin/inventory'
      preLoaderRoute: typeof AdminInventoryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/stores': {
      id: '/admin/stores'
      path: '/stores'
      fullPath: '/admin/stores'
      preLoaderRoute: typeof AdminStoresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_app/account/': {
      id: '/_app/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AppAccountIndexRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/addresses': {
      id: '/_app/account/addresses'
      path: '/addresses'
      fullPath: '/account/addresses'
      preLoaderRoute: typeof AppAccountAddressesRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/notifications': {
      id: '/_app/account/notifications'
      path: '/notifications'
      fullPath: '/account/notifications'
      preLoaderRoute: typeof AppAccountNotificationsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/payment-methods': {
      id: '/_app/account/payment-methods'
      path: '/payment-methods'
      fullPath: '/account/payment-methods'
      preLoaderRoute: typeof AppAccountPaymentMethodsRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/account/profile': {
      id: '/_app/account/profile'
      path: '/profile'
      fullPath: '/account/profile'
      preLoaderRoute: typeof AppAccountProfileRouteImport
      parentRoute: typeof AppAccountRoute
    }
    '/_app/category/$slug': {
      id: '/_app/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof AppCategorySlugRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout/': {
      id: '/_app/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof AppCheckoutIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/checkout/success': {
      id: '/_app/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof AppCheckoutSuccessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/': {
      id: '/_app/orders/'
      path: '/orders'
      fullPath: '/orders/'
      preLoaderRoute: typeof AppOrdersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orders/$id': {
      id: '/_app/orders/$id'
      path: '/orders/$id'
      fullPath: '/orders/$id'
      preLoaderRoute: typeof AppOrdersIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppAccountRouteChildren {
  AppAccountAddressesRoute: typeof AppAccountAddressesRoute
  AppAccountNotificationsRoute: typeof AppAccountNotificationsRoute
  AppAccountPaymentMethodsRoute: typeof AppAccountPaymentMethodsRoute
  AppAccountProfileRoute: typeof AppAccountProfileRoute
  AppAccountIndexRoute: typeof AppAccountIndexRoute
}

const AppAccountRouteChildren: AppAccountRouteChildren = {
  AppAccountAddressesRoute: AppAccountAddressesRoute,
  AppAccountNotificationsRoute: AppAccountNotificationsRoute,
  AppAccountPaymentMethodsRoute: AppAccountPaymentMethodsRoute,
  AppAccountProfileRoute: AppAccountProfileRoute,
  AppAccountIndexRoute: AppAccountIndexRoute,
}

const AppAccountRouteWithChildren = AppAccountRoute._addFileChildren(
  AppAccountRouteChildren,
)

interface AppRouteChildren {
  AppAboutRoute: typeof AppAboutRoute
  AppAccountRoute: typeof AppAccountRouteWithChildren
  AppBrandsRoute: typeof AppBrandsRoute
  AppCareersRoute: typeof AppCareersRoute
  AppCartRoute: typeof AppCartRoute
  AppContactRoute: typeof AppContactRoute
  AppCorporateRoute: typeof AppCorporateRoute
  AppForgotPasswordRoute: typeof AppForgotPasswordRoute
  AppHelpRoute: typeof AppHelpRoute
  AppLoginRoute: typeof AppLoginRoute
  AppPrivacyRoute: typeof AppPrivacyRoute
  AppRegisterRoute: typeof AppRegisterRoute
  AppReturnPolicyRoute: typeof AppReturnPolicyRoute
  AppReturnsRoute: typeof AppReturnsRoute
  AppSearchRoute: typeof AppSearchRoute
  AppShippingRoute: typeof AppShippingRoute
  AppStoresRoute: typeof AppStoresRoute
  AppTermsRoute: typeof AppTermsRoute
  AppWishlistRoute: typeof AppWishlistRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCategorySlugRoute: typeof AppCategorySlugRoute
  AppCheckoutSuccessRoute: typeof AppCheckoutSuccessRoute
  AppOrdersIdRoute: typeof AppOrdersIdRoute
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppCheckoutIndexRoute: typeof AppCheckoutIndexRoute
  AppOrdersIndexRoute: typeof AppOrdersIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAboutRoute: AppAboutRoute,
  AppAccountRoute: AppAccountRouteWithChildren,
  AppBrandsRoute: AppBrandsRoute,
  AppCareersRoute: AppCareersRoute,
  AppCartRoute: AppCartRoute,
  AppContactRoute: AppContactRoute,
  AppCorporateRoute: AppCorporateRoute,
  AppForgotPasswordRoute: AppForgotPasswordRoute,
  AppHelpRoute: AppHelpRoute,
  AppLoginRoute: AppLoginRoute,
  AppPrivacyRoute: AppPrivacyRoute,
  AppRegisterRoute: AppRegisterRoute,
  AppReturnPolicyRoute: AppReturnPolicyRoute,
  AppReturnsRoute: AppReturnsRoute,
  AppSearchRoute: AppSearchRoute,
  AppShippingRoute: AppShippingRoute,
  AppStoresRoute: AppStoresRoute,
  AppTermsRoute: AppTermsRoute,
  AppWishlistRoute: AppWishlistRoute,
  AppIndexRoute: AppIndexRoute,
  AppCategorySlugRoute: AppCategorySlugRoute,
  AppCheckoutSuccessRoute: AppCheckoutSuccessRoute,
  AppOrdersIdRoute: AppOrdersIdRoute,
  AppProductsIdRoute: AppProductsIdRoute,
  AppCheckoutIndexRoute: AppCheckoutIndexRoute,
  AppOrdersIndexRoute: AppOrdersIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminBannersRoute: typeof AdminBannersRoute
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminCouponsRoute: typeof AdminCouponsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDiscountsRoute: typeof AdminDiscountsRoute
  AdminInventoryRoute: typeof AdminInventoryRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminStoresRoute: typeof AdminStoresRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminBannersRoute: AdminBannersRoute,
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminCouponsRoute: AdminCouponsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDiscountsRoute: AdminDiscountsRoute,
  AdminInventoryRoute: AdminInventoryRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminStoresRoute: AdminStoresRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AdminRoute: AdminRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
